language: objective-c
osx_image: xcode9.3

before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild test -workspace CoinPrices.xcworkspace -scheme CoinPrices -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty -c

