language: objective-c
osx_image: xcode9.3
script:
    - xcodebuild clean test -project CoinPrices.xcodeproj -scheme CoinPrices -destination "platform=iOS Simulator,name=iPhone X,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

#osx_image: xcode9.3
#language: objective-c
## cache: cocoapods
## podfile: CoinPrices/Podfile
## before_install:
## - gem install cocoapods # Since Travis is not always on latest version
## - pod install --project-directory=CoinPrices
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace CoinPrices.xcworkspace -scheme CoinPrices -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty

